
theme: jekyll-theme-merlot
title: Liran Ziegelman
description: Peridot Data Consulting

remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

